### ISSUE TITLE
New URL for datafeed by LCPS as of today

### ISSUE THREAD

**Issue by wbijster** [Sikerdebaard/opencoronastats#11]
The new URL https://lcps.nu/wp-content/uploads/covid-19-datafeed.csv is available as of today and the old URL will not longer be available tomorrow.

Belangrijke update datafeed, 26-07-2021:

Wegens verbeterde beveiligingsprotocollen is de datafeed van het LCPS sinds vrijdag 23 juli voor enkele partijen niet meer bereikbaar.

Om deze reden wordt de datafeed vanaf vandaag (maandag 26 juli om 15.00 uur) via een andere URL beschikbaar gemaakt. De nieuwe url is vanaf 15:00 uur vandaag (26-7-2021) actief en vanaf morgen (27-07-2021) wordt de nieuwe data dagelijks bijgeschreven in de datafeed op de nieuwe url. De oude url komt daarmee te vervallen.

Maakt u gebruik van een automatische tool om de gegevens op te halen? Dan moet u daarin de url aanpassen.

De huidige url: https://lcps.nu/wp-content/uploads/covid-19.csv – vervalt dinsdag 27-07

Nieuwe url: https://lcps.nu/wp-content/uploads/covid-19-datafeed.csv – beschikbaar vanaf maandag 26-07 15.00uur.

**Comment by Sikerdebaard** [comment]
Interesting! Thanks for the warning, I'll update the url's in the scripts tonight.
